#eureka:
#  client:
#    register-with-eureka: false
#
#server:
#  port: 8222

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: books
#          uri: http://localhost:8091
#          predicates:
#            - Path=/api/v1/books/**
#        - id: authors
#          uri: http://localhost:8071
#          predicates:
#            - Path=/api/v1/authors/**
